config/routes.rb
Rails.application.routes.draw do
  resources :health_tips

  resources :products

  devise_for :admins
  
  root to: redirect("/admins/sign_in")

  get 'codes/authenticate'

  get 'codes/new', as: :admin_root
  post 'codes/generate'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/code.rb
class Code < ActiveRecord::Base
  belongs_to :product
  validates :code, presence: true, uniqueness: true

  enum status: %w(used unused)

  def used?
    self.status == 'used'
  end

  def unused?
    self.status == 'unused'
  end

  def used!
    self.update!(:status => 0)
  end

  def self.genuine code
    c = Code.find_by(:code => code)
    if c.try(:unused?)
      c.used!
      return 'unused'
    elsif c.try(:used?)
      return 'used'
    else
      return nil
    end
  end

  def self.generate number
    code_listings = []
    (1..number).each { |i| code_listings << Code.create(:code => rand.to_s[2...14]) }

    code_listings
  end
end

app/models/health_tip.rb
class HealthTip < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :codes, dependent: :destroy

  def self.empty?
    Product.all.length == 0
  end
end

app/models/token.rb
class Token < ActiveRecord::Base

  def self.exists? token
    Token.find_by :key => token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/codes_controller.rb
#require "#{Rails.root}/app/controllers/concerns/json_generate"

class CodesController < ApplicationController
  before_action :require_token, only: [:authenticate]
  before_action :authenticate_admin!, except: [:authenticate]

  def require_token
    unless Token.exists? params["token"]
      render json: JSONResponse.create("Authentication Failure", "You have provided an invalid key")
    end
  end

  def authenticate 
    response = Code.genuine params["code"]

    if response == 'used'
      render json: JSONResponse.create("500", "Code used", "This product code has already been used.")
    elsif response == 'unused'
      render json: JSONResponse.create("501", "Code valid", "The product you have bought is genuine.")
    else
      render json: JSONResponse.create("502", "Invalid Code", "The code you entered is not valid. Please report to the manufacturer.")
    end
  end

  def generate
    @codes = Code.generate(params[:code].to_i)
  end

  def new
  end

  private
    def code_params
      params.require(:code).permit(:code)
    end
end

app/controllers/concerns/json_generate.rb
class JSONResponse
  def self.create(status, title, msg)
    {
      "status" => status,
      "title" => title, 
      "message" => msg 
    }
  end
end

app/controllers/health_tips_controller.rb
class HealthTipsController < ApplicationController
  before_action :set_health_tip, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @health_tips = HealthTip.all
    respond_with(@health_tips)
  end

  def show
    respond_with(@health_tip)
  end

  def new
    @health_tip = HealthTip.new
    respond_with(@health_tip)
  end

  def edit
  end

  def create
    @health_tip = HealthTip.new(health_tip_params)
    @health_tip.save
    respond_with(@health_tip)
  end

  def update
    @health_tip.update(health_tip_params)
    respond_with(@health_tip)
  end

  def destroy
    @health_tip.destroy
    respond_with(@health_tip)
  end

  private
    def set_health_tip
      @health_tip = HealthTip.find(params[:id])
    end

    def health_tip_params
      params.require(:health_tip).permit(:category, :tip)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
  end

  def show
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/health_tips_helper.rb
module HealthTipsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/codes/authenticate.html.erb
<h1>Codes#authenticate</h1>
<p>Find me in app/views/codes/authenticate.html.erb</p>

app/views/codes/generate.html.erb
<%= link_to "Logout", destroy_admin_session_path, method: :delete %>
<br>
<%= link_to "back", admin_root_path %>
<br>
<h1>Codes#generate</h1>

<ol>
<% @codes.each do |code| %>
  <li><%= code.code %></li>
<% end %>
</ol>

app/views/codes/new.html.erb
<%= link_to "Logout", destroy_admin_session_path, method: :delete %>

<h1>Generate new batch of codes</h1>

<%= form_tag codes_generate_path do %>
  
  <p>Please enter the number of codes to generate: <%= number_field_tag :code %></p>
  <p><%= submit_tag "Generate" %></p>
<% end %>

app/views/health_tips/_form.html.erb
<%= form_for(@health_tip) do |f| %>
  <% if @health_tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@health_tip.errors.count, "error") %> prohibited this health_tip from being saved:</h2>

      <ul>
      <% @health_tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.number_field :category %>
  </div>
  <div class="field">
    <%= f.label :tip %><br>
    <%= f.text_area :tip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/health_tips/edit.html.erb
<h1>Editing health_tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @health_tip %> |
<%= link_to 'Back', health_tips_path %>

app/views/health_tips/index.html.erb
<h1>Listing health_tips</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Tip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @health_tips.each do |health_tip| %>
      <tr>
        <td><%= health_tip.category %></td>
        <td><%= health_tip.tip %></td>
        <td><%= link_to 'Show', health_tip %></td>
        <td><%= link_to 'Edit', edit_health_tip_path(health_tip) %></td>
        <td><%= link_to 'Destroy', health_tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health tip', new_health_tip_path %>

app/views/health_tips/new.html.erb
<h1>New health_tip</h1>

<%= render 'form' %>

<%= link_to 'Back', health_tips_path %>

app/views/health_tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @health_tip.category %>
</p>

<p>
  <strong>Tip:</strong>
  <%= @health_tip.tip %>
</p>

<%= link_to 'Edit', edit_health_tip_path(@health_tip) %> |
<%= link_to 'Back', health_tips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Manufacturer</th>
    <th>Distributor</th>
    <th>Manufacture Date</th>
    <th>Expiry Date</th>
  </tr>

  <% if !Product.empty? %>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.manufacturer %></td>
        <td><%= product.distributor %></td>
        <td><%= product.manufacture_date %></td>
        <td><%= product.expiry_date %></td>
      </tr>
    <% end %>
  <% else %>
    <%= form_for :product do |f| %>
      <tr>
        <td><%= f.text_field :name %></td>
        <td><%= f.text_field :manufacturer %></td>
        <td><%= f.text_field :distributor %></td>
        <td><%= f.date_field :manufacture_date %></td>
        <td><%= f.date_field :expiry_date %></td>
      </tr>
      <tr>
        <td colspan='4'></td>
        <td><%= f.submit "Add Product" %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>